// <auto-generated />
// 'using System' — imports the base .NET types; Guid and DateTime are used in the model
using System;
// 'using Microsoft.EntityFrameworkCore' — imports EF Core's core types (ModelBuilder, DbContext, etc.)
using Microsoft.EntityFrameworkCore;
// 'using Microsoft.EntityFrameworkCore.Infrastructure' — imports ModelSnapshot and DbContext attribute
using Microsoft.EntityFrameworkCore.Infrastructure;
// 'using Microsoft.EntityFrameworkCore.Metadata' — imports SQL Server-specific model builder extensions
using Microsoft.EntityFrameworkCore.Metadata;
// 'using Microsoft.EntityFrameworkCore.Storage.ValueConversion' — imports value converters used during model building
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
// 'using Payment.API.Infrastructure.Persistence' — imports PaymentDbContext so the snapshot can reference it
using Payment.API.Infrastructure.Persistence;

// '#nullable disable' — disables C# 8+ nullable reference type warnings in this auto-generated file
#nullable disable

// 'namespace' — scopes the snapshot class to the Migrations namespace
namespace Payment.API.Migrations
{
    // [DbContext(typeof(PaymentDbContext))] — attribute that associates this snapshot with PaymentDbContext;
    //   EF Core uses it to detect whether the model has changed since the last migration
    [DbContext(typeof(PaymentDbContext))]
    // 'partial' — allows the class to be split across multiple files; EF Core tooling may add to it
    // 'class PaymentDbContextModelSnapshot' — auto-generated class that captures the current EF Core model state
    // ': ModelSnapshot' — base class from EF Core Infrastructure; requires overriding BuildModel
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        // 'protected' — accessible within this class and derived classes; not public API
        // 'override' — replaces the base class's abstract BuildModel method with this implementation
        // 'ModelBuilder modelBuilder' — the fluent API object used to describe the database schema
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
// '#pragma warning disable 612, 618' — suppresses "obsolete member" warnings in auto-generated code
#pragma warning disable 612, 618
            // HasAnnotation — attaches arbitrary key/value metadata to the model;
            //   "ProductVersion" records which EF Core version generated this snapshot
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                // "Relational:MaxIdentifierLength" — tells EF Core the max length for DB object names (128 for SQL Server)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // UseIdentityColumns — configures SQL Server IDENTITY columns as the default value-generation strategy
            //   (auto-incrementing integers or GUIDs generated by the database)
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // modelBuilder.Entity<T> — begins the fluent configuration block for the Payment entity
            // The string overload uses the fully-qualified type name; 'b' is the EntityTypeBuilder
            modelBuilder.Entity("Payment.API.Domain.Entities.Payment", b =>
                {
                    // b.Property<Guid>("Id") — declares a property of type Guid named "Id" on the entity
                    b.Property<Guid>("Id")
                        // ValueGeneratedOnAdd — instructs EF Core (and the DB) to generate the value when a new row is inserted
                        //   For Guid, SQL Server uses newsequentialid() or the app generates a new Guid
                        .ValueGeneratedOnAdd()
                        // HasColumnType — maps the CLR type to a specific SQL Server column type
                        //   "uniqueidentifier" is SQL Server's 128-bit GUID column type
                        .HasColumnType("uniqueidentifier");

                    // 'decimal' — a 128-bit high-precision numeric type; ideal for monetary values to avoid floating-point errors
                    b.Property<decimal>("Amount")
                        // HasPrecision(10, 2) — sets the column to decimal(10,2): 10 total digits, 2 after the decimal point
                        //   This is the standard precision for currency amounts
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    // DateTime — a value type representing a point in time; stored as datetime2 in SQL Server
                    b.Property<DateTime>("CreatedAt")
                        // "datetime2" — SQL Server's high-precision date/time type (100-nanosecond resolution)
                        .HasColumnType("datetime2");

                    // 'string' — a reference type representing a sequence of Unicode characters
                    b.Property<string>("Currency")
                        // IsRequired — marks the column as NOT NULL in the database schema
                        .IsRequired()
                        // "nvarchar(max)" — SQL Server's variable-length Unicode string with no fixed upper bound
                        .HasColumnType("nvarchar(max)");

                    // Guid CustomerId — foreign-key reference to the customer; stored as uniqueidentifier
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerEmail")
                        // IsRequired — NOT NULL constraint; every payment must have a customer email
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    // Guid OrderId — foreign-key reference to the order that triggered this payment
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        // IsRequired — the payment status must always be present; no NULL allowed
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    // StripePaymentIntentId is nullable (no IsRequired) — optional field for Stripe integration
                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    // HasKey — defines the primary key for the entity; EF Core uses this to generate the PK constraint
                    b.HasKey("Id");

                    // ToTable — maps the entity to the "Payments" table in the database
                    b.ToTable("Payments");
                });
// '#pragma warning restore 612, 618' — re-enables the suppressed obsolete-member warnings
#pragma warning restore 612, 618
        }
    }
}
